version: '3'

services:
  feitcher-nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html:ro
    ports:
      - "8000:80"
    depends_on:
      - ${APP_NAME}_php
    networks:
      - app-network

  feitcher-php:
    container_name: ${APP_NAME}_php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - ${APP_NAME}_db
    networks:
      - app-network

  feitcher-db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - app-network

networks:
  app-network: